import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Welcome from "../components/organisms/Welcome/component";
import React, {useEffect, useState} from "react";
import {useRouter} from "next/router";
import Script from "next/script";

export default function Home() {
	const router = useRouter();
	const toLogin = () => {
		router.push('/registration');
	}
	return (
		<div className={styles.container}>
			<Head>
				<title>Jukte.kz</title>
				<meta name="description" content="Generated by create next app" />
				<Script src="https://api-maps.yandex.ru/2.1/?apikey=0fb09044-5132-48a3-8653-02425b40b298&lang=ru_RU"></Script>
				<link rel="icon" href="/public/favicon.ico" />
				<script>
					!function(f,b,e,v,n,t,s)
					{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
						n.callMethod.apply(n,arguments):n.queue.push(arguments)};
						if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
						n.queue=[];t=b.createElement(e);t.async=!0;
						t.src=v;s=b.getElementsByTagName(e)[0];
						s.parentNode.insertBefore(t,s)}(window, document,'script',
					'https://connect.facebook.net/en_US/fbevents.js');
					fbq('init', '8313696452034683');
					fbq('track', 'PageView');
				</script>
				<noscript><img height="1" width="1" style="display:none"
				               src="https://www.facebook.com/tr?id=8313696452034683&ev=PageView&noscript=1"
				/></noscript>

			</Head>

			<main className={styles.main}>
				<Welcome toLogin={toLogin} />
			</main>
		</div>
	)
}
