import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Welcome from "../components/organisms/Welcome/component";
import React, {useEffect, useState} from "react";
import {useRouter} from "next/router";
import Script from "next/script";

export default function Home() {
    const router = useRouter();
    const toLogin = () => {
        router.push('/registration');
    }
  return (
    <div className={styles.container}>
      <Head>
        <title>Jukte.kz</title>
        <meta name="description" content="Generated by create next app" />
        <Script src="https://api-maps.yandex.ru/2.1/?apikey=0fb09044-5132-48a3-8653-02425b40b298&lang=ru_RU"></Script>
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Welcome toLogin={toLogin} />
      </main>
    </div>
  )
}
